### ISSUE TITLE
dataone.css edits required

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone_lessons#179]
List of things for @datadavev to look at within the css file.  Please feel free to add to the list.

- [ ] Asterisk text style not working after a centered image (e.g. https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#24)
- [ ] Left aligned property required for a source (*text*)  under a centered image (e.g. https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#26)
- [ ] Need to be able to .center [ ] and .middle[ ] a single object vs the whole slide (e.g. https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#33)
- [ ] DLC sizing acting differently in slide sets

**Comment by hsoyka** [comment]
[] Remove "Footer text" from the cover.md template.
